// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARB3Fkml-HJOYMERYxug9P0Jd5GnTLT7E',
    appId: '1:70190198504:web:66fff95fbddc0c4cbb635d',
    messagingSenderId: '70190198504',
    projectId: 'transport-38f3c',
    authDomain: 'transport-38f3c.firebaseapp.com',
    storageBucket: 'transport-38f3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtw3uXD7CChTyXGFnNokNHOb-nrdGNBTU',
    appId: '1:70190198504:android:4f74d0bf519d76fcbb635d',
    messagingSenderId: '70190198504',
    projectId: 'transport-38f3c',
    storageBucket: 'transport-38f3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIFy3kD3x5ipP8pN9i77YUMgnUU688umw',
    appId: '1:521192685689:ios:b09e303feb8afb705014a8',
    messagingSenderId: '521192685689',
    projectId: 'stranger-4576f',
    storageBucket: 'stranger-4576f.firebasestorage.app',
    iosClientId: '521192685689-gl0e7o7adsep2dmj899rub1vn6sk7kjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.browser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARB3Fkml-HJOYMERYxug9P0Jd5GnTLT7E',
    appId: '1:70190198504:web:1241ba63d53b8286bb635d',
    messagingSenderId: '70190198504',
    projectId: 'transport-38f3c',
    authDomain: 'transport-38f3c.firebaseapp.com',
    storageBucket: 'transport-38f3c.firebasestorage.app',
  );

}